import type {
  BranReadinessProjection,
  CockpitSource,
  DiagnosticsProjection,
  FleetProjection,
  NetworkDevicesProjection,
} from '../cockpit-contract'

export const FIXTURE_TIME = '2026-08-03T12:00:00.000Z'

export function makeCockpitSource(
  overrides: Partial<CockpitSource> = {},
): CockpitSource {
  return {
    state: 'healthy',
    sourceAt: FIXTURE_TIME,
    observedAt: FIXTURE_TIME,
    lastSuccessAt: FIXTURE_TIME,
    projectedAt: FIXTURE_TIME,
    ageSecs: 0,
    staleAfterSecs: 90,
    diagnosticCodes: [],
    ...overrides,
  }
}

export function makeFleetProjection(
  overrides: Partial<FleetProjection> = {},
): FleetProjection {
  return {
    schema: 'lugos-fleet/v1',
    generatedAt: FIXTURE_TIME,
    sources: {
      agentMail: makeCockpitSource(),
      inventory: makeCockpitSource(),
      runtime: makeCockpitSource({ state: 'unknown', diagnosticCodes: ['source_not_enabled'] }),
    },
    summary: {
      connectedAgents: 1,
      staleAgents: 0,
      pendingHandoffs: 1,
      responseRequestedHandoffs: 1,
      targets: 2,
      targetExceptions: 1,
    },
    agents: [{
      agentAddress: '4070pc/codex',
      host: '4070pc',
      tool: 'codex',
      sessionId: 'session-1',
      repo: 'lugos',
      branch: 'master',
      task: 'operator cockpit',
      model: 'gpt-5.6-sol',
      presence: 'active',
      updatedAt: FIXTURE_TIME,
      ageSecs: 0,
    }],
    handoffScope: {
      mode: 'bounded_unacked_inbox',
      horizonHours: 72,
      pageLimit: 100,
      truncated: false,
    },
    handoffs: [{
      messageId: 351,
      threadId: 'thread-1',
      fromAgent: 'lugos-host/mission-control',
      toAgent: '4070pc/codex',
      kind: 'handoff',
      contextId: 'week-4',
      preview: 'Production verification requires acknowledgement.',
      responseRequested: true,
      createdAt: FIXTURE_TIME,
      ageSecs: 0,
    }],
    targets: [{
      slug: 'lugos-host',
      label: 'Lugos host',
      osFamily: 'linux',
      roles: ['utility-host'],
      lanAddress: '10.0.1.33',
      state: 'attention',
      diagnosticCodes: ['runtime_probe_partial'],
      expectedServices: [{ name: 'mission-control', expectedState: 'running' }],
      observedServices: [],
    }, {
      slug: '4070pc',
      label: '4070 PC',
      osFamily: 'windows',
      roles: ['operator'],
      lanAddress: '10.0.1.30',
      state: 'ready',
      diagnosticCodes: [],
      expectedServices: [],
      observedServices: [],
    }],
    ...overrides,
  }
}

export function makeDiagnosticsProjection(
  overrides: Partial<DiagnosticsProjection> = {},
): DiagnosticsProjection {
  const model = {
    state: 'healthy' as const,
    configured: true,
    listed: true,
    checkedAt: FIXTURE_TIME,
    ageSecs: 0,
    diagnosticCodes: [],
  }
  return {
    schema: 'lugos-cockpit-diagnostics/v1',
    generatedAt: FIXTURE_TIME,
    sources: {
      autosync: makeCockpitSource(),
      governance: makeCockpitSource({ staleAfterSecs: null }),
      repositories: makeCockpitSource({ staleAfterSecs: 120 }),
      monitors: makeCockpitSource(),
      models: makeCockpitSource(),
    },
    autosync: {
      state: 'healthy',
      lastTickAt: FIXTURE_TIME,
      lastSuccessAt: FIXTURE_TIME,
      lastAdvanceAt: null,
      lastAlertAt: null,
      ageSecs: 0,
      nextExpectedAt: '2026-08-03T12:30:00.000Z',
      repositoryRef: null,
      diagnosticCodes: [],
    },
    governance: {
      governanceId: 'lugos-scope-governance',
      policyVersion: '1.0.0',
      status: 'active',
      policyDigest: `sha256:${'a'.repeat(64)}`,
      warningMultiplier: 1.5,
      stopMultiplier: 2,
      verticalSliceBudgetFraction: 0.2,
      maxDesignReviewRounds: 2,
      scopeChangeApprover: 'operator',
      scopeChangeTriggers: ['new_runtime_process'],
      routingPolicy: {
        schemaVersion: '2',
        defaultTaskClass: 'implementation',
        defaultRiskTier: 'standard',
        outputCharacterLimit: 12_000,
        latencyOptInRoute: 'codex:spark-high',
        routes: [{
          taskClass: 'implementation',
          riskTier: 'standard',
          route: 'codex:sol-medium',
          serviceTier: 'quality',
        }],
      },
      activeExceptions: [],
    },
    repositories: {
      summary: {
        total: 2,
        ready: 1,
        attention: 1,
        dirty: 1,
        ahead: 0,
        behind: 0,
        detached: 0,
        missingUpstream: 0,
        pointerDrift: 0,
        checksFailing: 0,
        checksPending: 0,
        unknown: 0,
      },
      exceptions: [{
        repoId: 'parent',
        name: 'lugos',
        kind: 'parent',
        branch: 'master',
        head: 'a'.repeat(40),
        upstream: 'origin/master',
        ahead: 0,
        behind: 0,
        dirty: true,
        pointerState: 'not_applicable',
        checkState: 'passing',
        signals: ['dirty'],
        observedAt: FIXTURE_TIME,
        detailRef: 'repository/parent',
      }],
    },
    monitors: {
      summary: {
        total: 2,
        healthy: 2,
        degraded: 0,
        stale: 0,
        unavailable: 0,
        unknown: 0,
        directState: 'healthy',
        publicState: 'healthy',
      },
      monitors: [{
        monitorId: 'mc-direct',
        name: 'Mission Control direct',
        plane: 'direct',
        targetRef: 'mc-direct',
        state: 'healthy',
        uptime24h: 1,
        lastHeartbeatAt: FIXTURE_TIME,
        ageSecs: 0,
        staleAfterSecs: 90,
        diagnosticCodes: [],
        detailRef: 'monitor/mc-direct',
      }, {
        monitorId: 'mc-public',
        name: 'Mission Control public',
        plane: 'public',
        targetRef: 'mc-public',
        state: 'healthy',
        uptime24h: 1,
        lastHeartbeatAt: FIXTURE_TIME,
        ageSecs: 0,
        staleAfterSecs: 90,
        diagnosticCodes: [],
        detailRef: 'monitor/mc-public',
      }],
    },
    models: {
      gateway: model,
      ollama: model,
      gemini: {
        ...model,
        state: 'unknown',
        diagnosticCodes: ['gemini_health_unproven'],
      },
      aliases: [{
        alias: 'lugos-fast',
        provider: 'gemini',
        backendModel: 'gemini-2.5-flash',
        hostRef: 'external',
        configured: true,
        listed: true,
        state: 'unknown',
        fallbackAliases: ['lugos-fast-ollama'],
        diagnosticCodes: ['gemini_health_unproven'],
      }],
    },
    ...overrides,
  }
}

export function makeBranReadinessProjection(
  overrides: Partial<BranReadinessProjection> = {},
): BranReadinessProjection {
  return {
    schema: 'lugos-bran-checkout-readiness/v1',
    generatedAt: FIXTURE_TIME,
    source: makeCockpitSource(),
    summary: {
      total: 1,
      ready: 1,
      stale: 0,
      blocked: 0,
      assigned: 0,
      unknown: 0,
    },
    packs: [{
      packId: 'operator-handbook',
      title: 'Operator Handbook',
      latestRef: 'operator-handbook@2',
      latestVersion: 2,
      readyRef: 'operator-handbook@2',
      versionCount: 2,
      status: 'ready',
      sourceType: 'book',
      sourceAuthority: 'operator',
      trustTier: 'approved',
      freshnessPolicy: 'pinned',
      publishedAt: FIXTURE_TIME,
      importedAt: FIXTURE_TIME,
      ageSecs: 0,
      contentDigest: `sha256:${'b'.repeat(64)}`,
      custodyState: 'valid',
      assignmentState: 'unsupported',
      lastCheckoutAt: null,
      lastCheckoutAgent: null,
      blockingCodes: [],
      detailRef: 'bran/operator-handbook@2',
    }],
    ...overrides,
  }
}

export function makeNetworkDevicesProjection(
  overrides: Partial<NetworkDevicesProjection> = {},
): NetworkDevicesProjection {
  return {
    schema: 'lugos-network-devices/v1',
    generatedAt: FIXTURE_TIME,
    revision: 4,
    source: makeCockpitSource({ staleAfterSecs: 180 }),
    adapter: {
      kind: 'fixture',
      router: 'gl-b3000',
      pollSecs: 60,
      liveAfterSecs: 150,
      staleAfterSecs: 900,
      mutation: 'none',
    },
    summary: {
      total: 3,
      new: 2,
      live: 2,
      stale: 0,
      offline: 1,
      unknown: 0,
      changed: 0,
      managed: 1,
      randomized: 1,
    },
    devices: [{
      deviceId: 'dev-00005e005301',
      name: 'fixture-label-printer',
      inventoryState: 'provisional',
      connectionState: 'live',
      flags: ['new'],
      category: null,
      manufacturer: null,
      model: null,
      location: null,
      roles: [],
      targetSlug: null,
      mergedInto: null,
      firstSeenAt: FIXTURE_TIME,
      lastSeenAt: FIXTURE_TIME,
      lastSeenAgeSecs: 5,
      currentAddress: '10.0.1.163',
      observedHostname: 'fixture-label-printer',
      connection: 'wifi',
      reservation: 'dynamic',
      observationCount: 3,
      interfaces: [{
        interfaceId: 'if-00005e005301',
        kind: 'wifi',
        mac: '00:00:5E:00:53:01',
        privateAddress: false,
        connectionState: 'live',
        currentAddress: '10.0.1.163',
        observedHostname: 'fixture-label-printer',
        connection: 'wifi',
        ssid: 'Lugos-2G',
        firstSeenAt: FIXTURE_TIME,
        lastSeenAt: FIXTURE_TIME,
        leaseExpiresAt: '2026-08-04T00:00:00.000Z',
        reservation: 'dynamic',
        observationCount: 3,
      }],
      diagnosticCodes: [],
    }, {
      deviceId: 'dev-769335c39dd4',
      name: 'appleMac',
      inventoryState: 'provisional',
      connectionState: 'offline',
      flags: ['new', 'randomized_mac'],
      category: null,
      manufacturer: null,
      model: null,
      location: null,
      roles: [],
      targetSlug: null,
      mergedInto: null,
      firstSeenAt: '2026-08-03T11:00:00.000Z',
      lastSeenAt: '2026-08-03T11:20:00.000Z',
      lastSeenAgeSecs: 2_400,
      currentAddress: '10.0.1.111',
      observedHostname: 'appleMac',
      connection: 'wifi',
      reservation: 'dynamic',
      observationCount: 2,
      interfaces: [{
        interfaceId: 'if-769335c39dd4',
        kind: 'wifi',
        mac: '76:93:35:C3:9D:D4',
        privateAddress: true,
        connectionState: 'offline',
        currentAddress: '10.0.1.111',
        observedHostname: 'appleMac',
        connection: 'wifi',
        ssid: 'Lugos-5G',
        firstSeenAt: '2026-08-03T11:00:00.000Z',
        lastSeenAt: '2026-08-03T11:20:00.000Z',
        leaseExpiresAt: null,
        reservation: 'dynamic',
        observationCount: 2,
      }],
      diagnosticCodes: [],
    }, {
      deviceId: '4070pc',
      name: '4070pc',
      inventoryState: 'managed',
      connectionState: 'live',
      flags: [],
      category: 'computer',
      manufacturer: null,
      model: 'custom-desktop',
      location: 'office',
      roles: ['dev-machine'],
      targetSlug: '4070pc',
      mergedInto: null,
      firstSeenAt: '2026-08-03T11:00:00.000Z',
      lastSeenAt: FIXTURE_TIME,
      lastSeenAgeSecs: 0,
      currentAddress: '10.0.1.30',
      observedHostname: '4070pc',
      connection: 'ethernet',
      reservation: 'reserved',
      observationCount: 12,
      interfaces: [{
        interfaceId: 'if-e89c25c3ee99',
        kind: 'ethernet',
        mac: 'E8:9C:25:C3:EE:99',
        privateAddress: false,
        connectionState: 'live',
        currentAddress: '10.0.1.30',
        observedHostname: '4070pc',
        connection: 'ethernet',
        ssid: null,
        firstSeenAt: '2026-08-03T11:00:00.000Z',
        lastSeenAt: FIXTURE_TIME,
        leaseExpiresAt: null,
        reservation: 'reserved',
        observationCount: 12,
      }],
      diagnosticCodes: [],
    }],
    ...overrides,
  }
}
